using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShoppingAppDAL.Models
{
    [Table("Category")] //category table
    public class Category
    {
        [Key]
        [Column("ID")] //autogenerated
        public int CategoryId { get; set; } //refereed in product table
        [Required]
        [DataType("varchar")]
        [Column("Name")]
        [MaxLength(100, ErrorMessage = "Name cannot me more than 100 characters. Consider adding shortform")]
        public string CategoryName { get; set; }
    }
}
