using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShoppingAppDAL.Models
{
    [Table("Address")]
    public class Address
    {
        [Key]
        [Column("ID")] //autogenerated
        public int AddressId { get; set; }

        [Required]
        [DataType("int")]
        [Column("House Number")]
        public int AddressHouseNumber { get; set; }

        [Required]
        [DataType("varchar")]
        [Column("Building Name")]
        [MaxLength(50, ErrorMessage = "Name cannot me more than 50 characters. Consider adding shortform")]
        public string AddressBuildingName { get; set; }
        [Required]
        [DataType("varchar")]
        [Column("AreaOrColony Name")]
        [MaxLength(100, ErrorMessage = "Name cannot me more than 100 characters. Consider adding shortform")]
        public string AddressAreaName { get; set; }
        [DataType("varchar")]
        [Column("Type")]
        [MaxLength(10, ErrorMessage = "Name cannot me more than 100 characters. Consider adding shortform")]
        public string? AddressType { get; set; } 
        [Required]
        [DataType("int")]
        [Column("Pincode")]
        public int Pincode { get; set; }
        [Required]
        [DataType("string")]
        [Column("City")]
        public string City { get; set; }
        [Required]
        [DataType("state")]
        [Column("State")]
        public string State { get; set; }
        [ForeignKey("User")]
        public int? UserId { get; set; } //adding foreign key from user table //make sure it's non nullable
        public virtual User? User { get; set; }


    }
}
